# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 22:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_django_app', '0003_friend_is_friend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='first_name',
            new_name='friends_with',
        ),
        migrations.RenameField(
            model_name='friend',
            old_name='last_name',
            new_name='user',
        ),
    ]
