# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 22:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_django_app', '0004_auto_20160627_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='user',
        ),
        migrations.AddField(
            model_name='friend',
            name='name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='p_django_app.Register'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='friend',
            name='friends_with',
            field=models.IntegerField(),
        ),
    ]
