# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 01:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_django_app', '0007_remove_friend_friends_with'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='poked',
        ),
    ]
